### PR TITLE
Dynamic Cropping for Preview Images

### PR DESCRIPTION
**Pull request by AtaAtasoy**

### CODE REVIEW

**Comment by AtaAtasoy** [comment]
Warnings are treated as errors in the Github CI, which is the reason of the failed build.

**Comment by AtaAtasoy** [comment]
The first crop of the image is problematic. When we crop, the preview component renders and it resizes the preview. The preview resizes in such a way that the cropped area might go out of bounds or select an unintended place. We could fix this by adjusting flex value on the preview image, but then the preview starts to overlap with the annotation results since the flex values do not match.. I'm not sure on how to handle this

**Comment by AtaAtasoy** [comment]
Observe how the crop shifts to the bottom left 
screen-capture (5)

**Comment by Dogacel** [comment]
Just set the initial crop as the whole image

**Comment by AtaAtasoy** [comment]
Latest version 
screen-capture-_9_

**Review by Dogacel — APPROVED** [review]

**Pull request merged**
